- name: Setup dotfiles
  hosts: local
  tasks:
    - name: Create ghostty config directory
      file:
        path: ~/.config/ghostty
        state: directory

    - name: Link ghostty config
      file:
        src: "{{ playbook_dir }}/files/ghostty/config"
        dest: ~/.config/ghostty/config
        state: link

    - name: Create nvim config directory
      file:
        path: ~/.config/nvim
        state: directory

    - name: Link nvim config
      file:
        src: "{{ playbook_dir }}/files/nvim/init.lua"
        dest: ~/.config/nvim/init.lua
        state: link

    - name: Create zed config directory
      file:
        path: ~/.config/zed
        state: directory

    - name: Link zed config
      file:
        src: "{{ playbook_dir }}/files/zed/settings.json"
        dest: ~/.config/zed/settings.json
        state: link

    - name: Clone Tmux Plugin Manager if not exists
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        update: no

    - name: link tmux config
      file:
        src: "{{ playbook_dir }}/files/tmux/.tmux.conf"
        dest: ~/.tmux.conf
        state: link
