- name: Setup dotfiles
  hosts: local
  tasks:
    - name: Create ghostty config directory
      file:
        path: ~/.config/ghostty
        state: directory

    - name: Link ghostty config
      file:
        src: "{{ playbook_dir }}/files/ghostty/config"
        dest: ~/.config/ghostty/config
        state: link

    - name: Create nvim config directory
      file:
        path: ~/.config/nvim
        state: directory

    - name: Link nvim config
      file:
        src: "{{ playbook_dir }}/files/nvim/init.lua"
        dest: ~/.config/nvim/init.lua
        state: link

    - name: Create nvim lua directory
      file:
        path: ~/.config/nvim/lua
        state: directory

    - name: Link nvim options
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/opts.lua"
        dest: ~/.config/nvim/lua/opts.lua
        state: link

    - name: Link neovim keymaps
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/keymaps.lua"
        dest: ~/.config/nvim/lua/keymaps.lua
        state: link

    - name: Link neovim lazy setup
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/lazy-setup.lua"
        dest: ~/.config/nvim/lua/lazy-setup.lua
        state: link

    - name: create nvim plugins directory
      file:
        path: ~/.config/nvim/lua/plugins
        state: directory

    - name: Link nvim plugins
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/init.lua"
        dest: ~/.config/nvim/lua/plugins/init.lua
        state: link

    - name: Link nvim colorscheme
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/colorscheme.lua"
        dest: ~/.config/nvim/lua/plugins/colorscheme.lua
        state: link

    - name: Link nvim tree explorer
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/nvim-tree.lua"
        dest: ~/.config/nvim/lua/plugins/nvim-tree.lua
        state: link

    - name: Link nvim which key 
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/nvim-tree.lua"
        dest: ~/.config/nvim/lua/plugins/which-key.lua
        state: link

    - name: Link nvim telescope fuzzy finder 
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/telescope.lua"
        dest: ~/.config/nvim/lua/plugins/telescope.lua
        state: link

    - name: Link nvim greeting
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/alpha.lua"
        dest: ~/.config/nvim/lua/plugins/alpha.lua
        state: link

    - name: Create nvim plugins/lsp directory
      file:
        path: ~/.config/nvim/lua/plugins/lsp
        state: directory

    - name: Link nvim LSP mason config
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/lsp/mason.lua"
        dest: ~/.config/nvim/lua/plugins/lsp/mason.lua
        state: link

    - name: Link nvim LSP config
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/lsp/lspconfig.lua"
        dest: ~/.config/nvim/lua/plugins/lsp/lspconfig.lua
        state: link

    - name: Link nvim completion config
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/nvim-cmp.lua"
        dest: ~/.config/nvim/lua/plugins/nvim-cmp.lua
        state: link

    - name: Link nvim bufferline
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/bufferline.lua"
        dest: ~/.config/nvim/lua/plugins/bufferline.lua
        state: link

    - name: Link nvim lualine
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/lualine.lua"
        dest: ~/.config/nvim/lua/plugins/lualine.lua
        state: link

    - name: Link nvim dressing
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/dressing.lua"
        dest: ~/.config/nvim/lua/plugins/dressing.lua
        state: link

    - name: Link nvim vim-maximizer
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/vim-maximizer.lua"
        dest: ~/.config/nvim/lua/plugins/vim-maximizer.lua
        state: link

    - name: Link nvim treesitter
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/treesitter.lua"
        dest: ~/.config/nvim/lua/plugins/treesitter.lua
        state: link

    - name: Link nvim indent-blankline
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/indent-blankline.lua"
        dest: ~/.config/nvim/lua/plugins/indent-blankline.lua
        state: link

    - name: Link nvim autopairs
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/autopairs.lua"
        dest: ~/.config/nvim/lua/plugins/autopairs.lua
        state: link

    - name: Link nvim formatting
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/formatting.lua"
        dest: ~/.config/nvim/lua/plugins/formatting.lua
        state: link

    - name: Link nvim linting
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/linting.lua"
        dest: ~/.config/nvim/lua/plugins/linting.lua
        state: link

    - name: Link nvim gitsigns
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/gitsigns.lua"
        dest: ~/.config/nvim/lua/plugins/gitsigns.lua
        state: link

    - name: Link nvim lazygit
      file:
        src: "{{ playbook_dir }}/files/nvim/lua/plugins/lazygit.lua"
        dest: ~/.config/nvim/lua/plugins/lazygit.lua
        state: link

    - name: Create zed config directory
      file:
        path: ~/.config/zed
        state: directory

    - name: Link zed config
      file:
        src: "{{ playbook_dir }}/files/zed/settings.json"
        dest: ~/.config/zed/settings.json
        state: link

    - name: Clone Tmux Plugin Manager if not exists
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        update: no

    - name: Clone fzf-git.sh if not exists
      git:
        repo: https://github.com/junegunn/fzf-git.sh.git
        dest: ~/fzf-git.sh
        update: no

    - name: Link tmux config
      file:
        src: "{{ playbook_dir }}/files/tmux/.tmux.conf"
        dest: ~/.tmux.conf
        state: link

    - name: Link zsh config
      file:
        src: "{{ playbook_dir }}/files/zsh/.zshrc"
        dest: ~/.zshrc
        state: link

    - name: Create starship config directory
      file:
        path: ~/.config/starship
        state: directory

    - name: Link starship config
      file:
        src: "{{ playbook_dir }}/files/starship/starship.toml"
        dest: ~/.config/starship/starship.toml
        state: link
