# Starship Configuration

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Format configuration
format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "🌱 "
format = "[$symbol$branch]($style) "
style = "bold green"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"

[python]
symbol = "🐍 "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = "⬢ "
format = "[$symbol($version )]($style)"

[rust]
symbol = "🦀 "
format = "[$symbol($version )]($style)"

[golang]
symbol = "🐹 "
format = "[$symbol($version )]($style)"

[cmd_duration]
min_time = 2_000
format = "took [$duration]($style) "
style = "bold yellow"
